#!/usr/bin/env bash
# Sync files from system to dot

while read files
do
    IFS=" "
    set $files
    file_from="${1/#\~/$HOME}"
    file_to="${2/#\~/$HOME}"

    #echo cp $file_to $file_from
    cp -v $file_to $file_from

    unset IFS
done < ./FILEMAP
