#!/bin/python

import os
import shutil

configs = {
    '.config/bspwm/bspwmrc': '~/.config/bspwm/bspwmrc',
    '.config/dunst/dunstrc': '~/.config/dunst/dunstrc',
    '.config/gtk-3.0/bookmarks': '~/.config/gtk-3.0/bookmarks',
    '.config/gtk-3.0/settings.ini': '~/.config/gtk-3.0/settings.ini',
    '.config/herbstluftwm/autostart': '~/.config/herbstluftwm/autostart',
    '.config/herbstluftwm/panel.sh': '~/.config/herbstluftwm/panel.sh',
    '.config/sxhkd/sxhkdrc': '~/.config/sxhkd/sxhkdrc',
    '.config/termite/config': '~/.config/termite/config',
    '.config/tint2/default.tint2rc': '~/.config/tint2/default.tint2rc',
    '.config/tint2/tint2confrc': '~/.config/tint2/tint2confrc',
    '.config/tint2/tint2rc': '~/.config/tint2/tint2rc',
    'bin/powerline-shell.py': '~/bin/powerline-shell.py',
    'bin/puush': '~/bin/puush',
    'bin/sshot': '~/bin/sshot',
    '.ctags': '~/.ctags',
    '.emacs': '~/.emacs',
    '.gimp-2.8/fonts.conf': '~/.gimp-2.8/fonts.conf',
    '.gtkrc-2.0': '~/.gtkrc-2.0',
    '.tmux.conf': '~/.tmux.conf',
    '.vimrc': '~/.vimrc',
    '.weechat/alias.conf': '~/.weechat/alias.conf',
    '.weechat/buffers.conf': '~/.weechat/buffers.conf',
    '.weechat/irc.conf': '~/.weechat/irc.conf',
    '.weechat/iset.conf': '~/.weechat/iset.conf',
    '.weechat/weechat.conf': '~/.weechat/weechat.conf',
    '.xinitrc': '~/.xinitrc',
    '.zshrc': '~/.zshrc',
    'infinality-settings': '/etc/X11/xinit/xinitrc.d/infinality-settings.sh',
    '.Xresources': '~/.Xresources',
}

for file_dot, file_home in configs.items():
    home_path = os.path.expanduser(file_home)
    if (os.access(home_path, os.F_OK)):
        try:
            shutil.copyfile(home_path, file_dot)
        except Exception:
            pass
