#!/bin/python2

import os
import shutil

configs = [
    ('bin/powerline-shell.py', '~/bin/powerline-shell.py'),
    ('bin/puush', '~/bin/puush'),
    ('bin/sshot', '~/bin/sshot'),
    ('bspwm/bspwmrc', '~/.config/bspwm/bspwmrc'),
    ('dunst/dunstrc', '~/.config/dunst/dunstrc'),
    ('emacs/.spacemacs', '~/.spacemacs'),
    ('fish/config.fish', '~/.config/fish/config.fish'),
    ('fish/functions/fish_prompt.fish',
     '~/.config/fish/functions/fish_prompt.fish'),
    ('fish/functions/mark.fish', '~/.config/fish/functions/mark.fish'),
    ('gimp/fonts.conf', '~/.gimp-2.8/fonts.conf'),
    ('herbstluftwm/autostart', '~/.config/herbstluftwm/autostart'),
    ('herbstluftwm/panel.sh', '~/.config/herbstluftwm/panel.sh'),
    ('infinality/infinality-settings', '/etc/X11/xinit/xinitrc.d/infinality-settings.sh'),
    ('sxhkd/sxhkdrc', '~/.config/sxhkd/sxhkdrc'),
    ('termite/config', '~/.config/termite/config'),
    ('tint2/tint2rc', '~/.config/tint2/tint2rc'),
    ('tmux/.tmux.conf', '~/.tmux.conf'),
    ('vim/vimrc', '~/.vim/vimrc'),
    ('weechat/alias.conf', '~/.weechat/alias.conf'),
    ('weechat/buffers.conf', '~/.weechat/buffers.conf'),
    ('weechat/irc.conf', '~/.weechat/irc.conf'),
    ('weechat/iset.conf', '~/.weechat/iset.conf'),
    ('weechat/weechat.conf', '~/.weechat/weechat.conf'),
    ('xorg/.xResources', '~/.xResources'),
    ('xorg/.xinitrc', '~/.xinitrc'),
    ('zsh/.zshrc', '~/.zshrc'),
]

for (file_dot, file_home) in configs:
    home_path = os.path.expanduser(file_home)
    if (os.access(home_path, os.F_OK)):
        try:
            shutil.copyfile(home_path, file_dot)
        except Exception:
            print "Could not find %s" % home_path
            pass
