#! /bin/sh

bspc desktop --rename Desktop01 1
bspc monitor --add-desktops 2 3 4 5 6 7 8 9

bspc config border_width        1
bspc config window_gap          8

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config adaptative_raise    true

bspc config focused_border_color #000000
bspc config active_border_color #FFFFFF

bspc config focus_follows_pointer true

bspc config top_padding 15

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
