#!/bin/bash
# vim: fdm=marker

# Shorthand alias
hc() {
        herbstclient "$@"
}

#  Initialise
hc emit_hook reload

# Remove all existing keybindings
hc keyunbind --all

# 
#  Keybindings
# Super key as the main modifier
Mod=Mod4

# General keybinds

hc keybind $Mod-Alt-a  adb shell input keyevent 82

# WM keybinds

hc keybind $Mod-Ctrl-q  quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w       close
hc keybind $Mod-Return  spawn alacritty
hc keybind $Mod-Shift-Return  spawn /root/bin/winselect
hc keybind $Mod-space   spawn dmenu_run -i -p "Run: " -fn "Roboto-10:Bold" -nb "#333333" -sb "#696969"
hc keybind $Mod-Ctrl-s  systemctl suspend

# Focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up

hc keybind $Mod-l     focus right

# Focus
hc keybind $Mod-slash       cycle_monitor
hc keybind $Mod-Shift-slash shift_to_monitor +1
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-q           cycle +1
hc keybind $Mod-Shift-q     cycle -1
hc keybind $Mod-i           jumpto urgent

# Cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-period move_index +1 --skip-visible
hc keybind $Mod-Shift-comma  move_index -1 --skip-visible

# Moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# Splitting frames
# j - u; l - o
hc keybind $Mod-u             split bottom  0.5
hc keybind $Mod-o             split right   0.5
hc keybind $Mod-i             split explode

hc keybind $Mod-e     remove

# Resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left  +$resizestep
hc keybind $Mod-Control-j       resize down  +$resizestep
hc keybind $Mod-Control-k       resize up    +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize right -$resizestep
hc keybind $Mod-Control-Down    resize up    -$resizestep
hc keybind $Mod-Control-Up      resize down  -$resizestep
hc keybind $Mod-Control-Right   resize left  -$resizestep

hc keybind XF86AudioRaiseVolume spawn sh -c "~/bin/adjustvolume up; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86AudioLowerVolume spawn sh -c "~/bin/adjustvolume down; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86AudioMute spawn sh -c "~/bin/adjustvolume mute; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"

hc keybind XF86MonBrightnessUp spawn sh -c "~/bin/adjustbright up"
hc keybind XF86MonBrightnessDown spawn sh -c "~/bin/adjustbright down"


# Toggle layout
hc keybind $Mod-Shift-space cycle_layout 1
hc keybind $Mod-Shift-a     set_layout grid
hc keybind $Mod-Shift-s     set_layout max
hc keybind $Mod-Shift-d     set_layout vertical
hc keybind $Mod-Shift-f     set_layout horizontal
hc keybind $Mod-a           floating   toggle
hc keybind $Mod-s           fullscreen toggle
hc keybind $Mod-d           pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# 
#  Tag configs
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# 
#  General
hc set autodetect_monitors 1
hc set update_dragged_clients 0

# default layout for new frame: monocle/max
hc set default_frame_layout 2

hc set window_gap -1
hc set frame_padding 0
hc set frame_gap 10

hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc set swap_monitors_to_get_tag 0

hc set raise_on_focus_temporarily 1

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# 
#  Theme
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#ffffff'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set always_show_frame 0

hc set window_border_active_color '#222222'
hc set window_border_normal_color '#101010'
hc set window_bg_normal_color '#565656'
hc set window_bg_active_color '#345F0C'
hc set window_border_width 1

hc set gapless_grid 0

hc set_attr theme.active.color '#9fbc00'
hc set_attr theme.active.inner_color '#3E4A00'
hc set_attr theme.active.outer_color '#3E4A00'

hc set_attr theme.normal.color '#454545'

hc set_attr theme.urgent.color orange

hc set_attr theme.floating.border_width 0
hc set_attr theme.floating.outer_color black
hc set_attr theme.floating.outer_width 0

hc set_attr theme.background_color '#141414'
# hc set_attr theme.border_width 0
hc set_attr theme.inner_color black
# hc set_attr theme.inner_width 0

# 
#  Rules

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on

hc rule title='Untitled' floating=on

# 
#  Miscellaneous

# Unlock, just to be sure
hc unlock

hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc set_monitors 1920x1080+0+0 1920x1080+1920+0
hc pad 0 25
hc pad 1 25
# or simply:
hc detect_monitors

# Panel
tint2 &

# Keyboard (for when .xinitrc isn't called)
setxkbmap -variant altgr-intl -option compose:rctrl -option ctrl:nocaps

# Touchpad (for when .xinitrc isn't called)
xinput set-prop "SynPS/2 Synaptics TouchPad" 'Synaptics Scrolling Distance' -200 -200

# Wallpaper (for when .xinitrc isn't called)
~/.fehbg
